name: Second Workflow

on:
  workflow_call:
    inputs:
      pipelineType:
        required: true
        type: string
      buildTool:
         required: true
         type: string
  workflow_run:
    workflows: ["Main Workflow"]
    types:
      - completed

jobs:
  second_job:
    runs-on: ubuntu-latest

    steps:
      - name: Deserialize Inputs
        run: |
          echo "Received pipelineType: ${{inputs.pipelineType}}"
          echo "Received buildTool: ${{inputs.buildTool}}"
