name: Second Workflow

on:
  workflow_call:
  workflow_dispatch:
    
  workflow_run:
    workflows: ["Main Workflow"]
    types:
      - completed

jobs:
  second_job:
    runs-on: ubuntu-latest

    env:  # Define environment variables specific to this job
      pipelineType: ${{ github.event.inputs.pipelineType }}
      buildTool: ${{ github.event.inputs.buildTool  }}
      
    outputs:
      pipelineType: ${{steps.read_config.outputs.pipelineType}}
      buildTool:  ${{steps.read_config.outputs.buildTool}}
    

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Install jq and yq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq
          sudo curl -sL https://github.com/mikefarah/yq/releases/download/v4.13.2/yq_linux_amd64 -o /usr/bin/yq
          sudo chmod +x /usr/bin/yq

      - name: Read pipelineconfig
        id: read_config
        run: |
          pipeline_config_path="${{ github.workspace }}/pipelineconfig.yml"

          # Use a tool like yq to parse the YAML file (install yq if needed)
          pipelineType=$(yq eval '.pipelineType' "${pipeline_config_path}")
          buildTool=$(yq eval '.buildTool' "${pipeline_config_path}")
          echo "PipelineType: $pipelineType"
          echo "BuildTool: $buildTool"
          echo "pipelineType=$pipelineType" >> $GITHUB_OUTPUT
          echo "buildTool=$buildTool" >> $GITHUB_OUTPUT
          echo "pipelineType=$pipelineType" >> $GITHUB_ENV
          echo "buildTool=$buildTool" >> $GITHUB_ENV
          
      - name: Debug Pipeline Type and Build Tool
        run: |
          echo "Pipeline Type: ${{env.pipelineType}}"
          echo "Build Tool: ${{env.buildTool}}"

          
      - name: Conditional Step
        run: |
          if [ "${{env.pipelineType}}" == "java" ]; then
            if [ "${{env.buildTool}}" == "maven" ]; then
               echo "Running Maven Build"
               triggered_workflow="maven_build"
            elif [ "${{env.buildTool}}" == "ant" ]; then
                 echo "Running Ant Build"
                 triggered_workflow="ant_build"
            else
                echo "Unknown Build Tool: ${{env.buildTool}}"
               # Add handling for other build tools or unknown build tool
            fi
          else
            echo "Not a Java Pipeline"
            # Add handling for non-Java pipelines
          fi
    
             # Trigger the selected workflow using the `workflow_run` event
    
          if [ -n "$triggered_workflow" ]; then
             echo "Triggering workflow: mavenBuild.yml"
             # Use the workflow name or file path to trigger the workflow
             workflow_run_id=$(gh workflow run mavenBuild.yml \
             --ref "${{ github.ref }}" \
            --json id)
             echo "Triggered workflow with ID: $workflow_run_id"
          fi

          



#  CallMavenbuild:
#    needs: second_job
#    if: ${{ needs.second_job.outputs.pipelineType == 'java' && needs.second_job.outputs.buildTool == 'maven' }}
#    uses: Aish19999/DevOps_templet/.github/workflows/mavenBuild.yml@6af9461f89d67b217dd61c74ebe0c18af7a9a513
  
   
 
