name: Second Workflow

on:
  workflow_run:
    workflows: ["Main Workflow"]
    types:
      - completed

jobs:
  second_job:
    runs-on: ubuntu-latest

    steps:
      - name: Deserialize Inputs
        run: |
          pipelineType=${{ fromJson(github.event.inputs.pipelineType) }}
          buildTool=${{ fromJson(github.event.inputs.buildTool) }}
          echo "Received pipelineType: $pipelineType"
          echo "Received buildTool: $buildTool"
