name: Main Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Add your other build steps here

  trigger_dispatch:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Trigger Workflow Dispatcher
        uses: Aish19999/DevOps_templet/.github/scripts/trigger-workflow.sh@main
        with:
          buildTool: maven

