name: Second Workflow

on:
  workflow_call:
  workflow_run:
    workflows: ["Main Workflow"]
    types:
      - completed

jobs:
  second_job:
    runs-on: ubuntu-latest

    steps:
      - name: Deserialize Inputs
        run: |
          inputs="${{ github.event.inputs }}"
          pipelineType=$(echo "$inputs" | jq -r '.pipelineType')
          buildTool=$(echo "$inputs" | jq -r '.buildTool')
          echo "Received pipelineType: $pipelineType"
          echo "Received buildTool: $buildTool"
