name: Java maven build

on:
  workflow_call:
  workflow_dispatch:
  workflow_run:
    workflows: ["Second Workflow"]
    types:
      - completed

jobs:
  securityScan:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Security scan
      run: |
          echo "Runnning security scan"

     
     
