name: Java maven build

on:
  workflow_call:
  workflow_dispatch:
  workflow_run:
    workflows: ["Second Workflow"]
    types:
      - completed

jobs:
  sonarScan:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'temurin'
        cache: ant

    - name: Sonar Analysis  
      run: |
          echo "analysing the code"

     
     
